name: Test de workflow
run-name: ${{ github.actor }} is testing GitHub Actions
on: [push]
jobs:
  install-deps-and-cache:
      runs-on: ubuntu-latest
      steps:
        - uses: action/checkout@v3
        - uses: action/setup-node@v3
          with:
              node-version: '18'
        - run: |
            npm install
            npm run build
        - name: Cache modules
          uses: actions/cache@v3
          with:
            path: node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

  tests:
    runs-on: ubuntu-latest
    needs: install-deps-and-cache
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - run: npm run e2e:headless
      - uses: actions/upload-artifact@v3
        if: ${{ failure() || success() }}
        with:
          name: video
          path: cypress/videos/app.cy.ts.mp4