name: Test de workflow
run-name: ${{ github.actor }} is testing GitHub Actions
on: [push]
jobs:
  install-deps-and-cache:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
              node-version: '18'
        - name: Cache modules
          uses: actions/cache@v3
          with:
            path: |
              node_modules
              /home/runner/.cache/Cypress
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        - run: |
            npm install
            npm run build
  tests:
    runs-on: ubuntu-latest
    needs: install-deps-and-cache
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress

          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - run: npm run e2e:headless
      - uses: actions/upload-artifact@v3
        if: ${{ failure() || success() }}
        with:
          name: video
          path: cypress/videos/app.cy.ts.mp4
  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
       - uses: D3rHase/ssh-command-action
         with:
            host: ${{secrets.IP}} # Remote server address / ip - required
            user: ${{secrets.USERNAME}} # Remote server user - required
            private_key: ${{secrets.SSH}} # Private ssh key registered on the remote server - required
            command: cd with-cypress-app;git pull;killall node;npm run build && npm run start # Command to be executed - Default: echo 'hello world' - optional
