name: Test de workflow
run-name: ${{ github.actor }} is testing GitHub Actions
on: [push]
jobs:

  deploy:
    runs-on: ubuntu-latest
    #needs: tests
    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
            ssh-private-key: ${{ secrets.SSH }}
      - run: ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.IP }} "ls"