name: Build and Deploy

run-name: Build and Deploy

on: push

jobs:
  build-next-application:
    runs-on: ubuntu-22.04 #Mettre ubuntu-latest revient au même
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - run: npm install
      - run: npm run build

  build-docker-images-developpement:
    needs: build-next-application
    if: github.ref == 'refs/heads/develop'
    environment:
      name: developpement
      url: http://34.201.241.107:3000
    runs-on: ubuntu-22.04 #Mettre ubuntu-latest revient au même
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Build and Push Docker images to Github Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/yukig59/next-docker:dev

  build-docker-images-production:
    needs: build-next-application
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: http://34.201.241.107:3000/
    runs-on: ubuntu-22.04 #Mettre ubuntu-latest revient au même
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Build and Push Docker images to Github Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/yukig59/next-docker:latest