name: Test de workflow
run-name: ${{ github.actor }} is testing GitHub Actions
on: [push]
jobs:
  build-next-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install and Build
      - uses: actions/setup-node@v3
        with:
            node-version: '18'
      - run: npm install
      - run: npm run build
      - run: npm run e2e:headless
      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: video
          path: cypress/videos/app.cy.ts.mp4