name: Test de workflow
run-name: ${{ github.actor }} is testing GitHub Actions
on: [push]
jobs:

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH }}
          known_hosts: unnecessary
      - run: ssh -i ~/.ssh/id_rsa ${{ env.USERNAME }}@${{ env.IP }} -e "killall node; cd with-cypress-app; git pull; npm i && npm run build && npm run start"